# Generated by Django 3.1.7 on 2021-06-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=40)),
                ('data_nasc', models.DateField()),
                ('dono', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_pets.animal_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': 'animal',
            },
        ),
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.animal')),
                ('cor_pelo', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'cachorro',
            },
            bases=('pets.animal',),
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.animal')),
                ('cor_pelo', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'gato',
            },
            bases=('pets.animal',),
        ),
        migrations.CreateModel(
            name='Passaro',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pets.animal')),
                ('cor_pena', models.CharField(max_length=80)),
                ('licensa_ambiental', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'passaro',
            },
            bases=('pets.animal',),
        ),
    ]
